version: "2"
services:
  secrets-driver:
    environment:
      RANCHER_DEBUG: true
    image: rancher/storage-secrets:v0.6.8
    labels:
      io.rancher.container.agent.role: environment,agent
      io.rancher.container.create_agent: "true"
      io.rancher.scheduler.global: "true"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 25m
    network_mode: host
    privileged: true
    storage_driver:
      create_supported: false
      description: A tmpfs driver for secrets
      name: rancher-secrets
      scope: local
      start_on_create: true
      volume_access_mode: singleHostRW
      volume_capabilities:
      - secrets
    volumes:
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
