version: "2"
services:
  network-policy-manager:
    image: rancher/network-policy-manager:v0.1.0
    labels:
      io.rancher.scheduler.global: "true"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 25m
    network_mode: host
    pid: host
    privileged: true
