version: "2"
services:
  dns:
    command: rancher-dns --metadata-server=localhost --answers=/etc/rancher-dns/answers.json
    image: rancher/dns:v0.13.3
    labels:
      io.rancher.scheduler.global: "true"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 25m
    network_mode: container:metadata
  metadata:
    cap_add:
    - NET_ADMIN
    command: start.sh rancher-metadata -subscribe
    image: rancher/metadata:v0.7.1
    labels:
      io.rancher.container.agent_service.metadata: "true"
      io.rancher.container.create_agent: "true"
      io.rancher.scheduler.global: "true"
      io.rancher.sidekicks: dns
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 25m
    network_mode: bridge
  network-manager:
    command: plugin-manager --metadata-url http://169.254.169.250/2016-07-29
    environment:
      DOCKER_BRIDGE: docker0
      METADATA_IP: 169.254.169.250
    image: rancher/network-manager:v0.4.5
    labels:
      io.rancher.scheduler.global: "true"
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 25m
    network_mode: host
    pid: host
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    - /lib/modules:/lib/modules:ro
    - /run:/run:ro
    - /var/run:/var/run:ro
    - rancher-cni-driver:/etc/cni
    - rancher-cni-driver:/opt/cni
