zk:
  tty: true
  image: rawmind/rancher-zk:3.4.7
  volumes:
  - /opt/zookeeper/data
  environment:
  - JVMFLAGS=-Xmx${zk_mem}m -Xms${zk_mem}m
  - CONFD_INTERVAL=${zk_interval}
broker:
  tty: true
  image: rawmind/rancher-kafka:0.8.2
  links:
  - 'zk:'
  volumes:
  - /opt/kafka/data
  environment:
  - KAFKA_HEAP_OPTS=-Xmx${kafka_mem}m -Xms${kafka_mem}m
  - CONFD_INTERVAL=${kafka_interval}
