
rancher-ingress-controller:
    image: rancher/lb-service-rancher:v0.4.0
    labels:
        io.rancher.scheduler.affinity:host_label_soft: orchestration=true
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent.role: environment
    environment:
        KUBERNETES_URL: http://kubernetes.kubernetes.rancher.internal
    command:
        - lb-controller
        - --controller=kubernetes
        - --provider=rancher
    links:
        - kubernetes
