convoy:
    image: wlan0/meta-convoy
    privileged: true
    pid: host
    net: host
    labels:
        io.rancher.scheduler.global: 'true'
        io.rancher.container.dns: 'true'
        io.rancher.container.create_agent: 'true'
        io.rancher.container.pull_image: always
        io.rancher.service.selector.container: 'selector.convoy.nfs=true'
storagepool:
    image: wlan0/convoy-nfs-storagepool-agent
    labels:
        io.rancher.scheduler.global: 'true'
        io.rancher.container.create_agent: 'true'
        io.rancher.container.pull_image: always
