.catalog:
    name: Scheduler
    description: A resource based scheduler plugin for Rancher.
    version: v0.4.0
    minimum_rancher_version: v1.1.999
    questions:
        - variable: "RANCHER_DEBUG"
          label: "Enable Debug Logs"
          description: "This will enable very verbose debug logs."
          type: "boolean"
          default: "true"
          required: true

scheduler:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
