#!/bin/bash
set -e

cd $(dirname $0)/..

trap "rm -rf /scratch/*" exit

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ -n "${DRONE_BRANCH}" ] && [ "${DRONE_BRANCH}" != "${GIT_BRANCH}" ]; then
    git checkout -b ${DRONE_BRANCH}
    GIT_BRANCH=${DRONE_BRANCH}
fi

if [ "$GIT_BRANCH" != "master" ]; then
  sed -i "s#master#$GIT_BRANCH#" ./scripts/repo.json
fi

if [ -d "/scratch" ]; then
    rsync -a --exclude .tox ./ /scratch
fi

pushd /scratch/integration

/usr/bin/rancher-catalog-service -catalogUrl ../ -refreshInterval 7200 > /dev/null 2>&1 &

# hang out until the service is up and listening on tcp/8088
while true; do
    echo 'Waiting for Rancher Catalog service to become available on localhost:8088...'
    set +e ; curl -s --connect-timeout 2 http://localhost:8088
    if [ "0" == "$?" ]; then
      echo 'Succesful connection to Catalog Service on localhost:8088.'
      set -e
      break
    fi
done

tox -e flake8,py27
popd
